from .calidad import IncidenciaDatos, Origen
from .documentos import Documento, PaginaDocumento, TrabajoProcesamiento
from .ejecucion import EstimacionPropuesta, Fichaje, IncidenciaProduccion, Notificacion
from .fabricacion import (
    Aparato,
    Articulo,
    Bulto,
    ComponenteBulto,
    DependenciaOF,
    LineaOF,
    OFAparato,
    Operacion,
    OrdenFabricacion,
    ProgramaCNC,
    Tanda,
)
from .plan import AsignacionPlan, CambioPlan, Plan
from .recursos import (
    Ausencia,
    Cualificacion,
    Festivo,
    JornadaExtra,
    Operario,
    ParadaRecurso,
    Recurso,
    ReglaDependencia,
    Seccion,
    TiempoEstandar,
    Turno,
)
from .seguridad import Auditoria, ParametroConfig, Usuario

__all__ = [
    "Aparato",
    "Articulo",
    "AsignacionPlan",
    "Auditoria",
    "Ausencia",
    "Bulto",
    "CambioPlan",
    "ComponenteBulto",
    "Cualificacion",
    "DependenciaOF",
    "Documento",
    "EstimacionPropuesta",
    "Festivo",
    "JornadaExtra",
    "Fichaje",
    "IncidenciaDatos",
    "IncidenciaProduccion",
    "LineaOF",
    "Notificacion",
    "OFAparato",
    "Operacion",
    "Operario",
    "OrdenFabricacion",
    "Origen",
    "PaginaDocumento",
    "ParadaRecurso",
    "ParametroConfig",
    "Plan",
    "ProgramaCNC",
    "Recurso",
    "ReglaDependencia",
    "Seccion",
    "Tanda",
    "TiempoEstandar",
    "TrabajoProcesamiento",
    "Turno",
    "Usuario",
]
